### ISSUE TITLE
At certain window sizes, the Tutorials page content is hidden by the menu bar

### ISSUE THREAD

**Issue by Infinidoge** [LambdAurora/lambdaurora.github.io#2]
![image](https://user-images.githubusercontent.com/22727114/187569303-420adc3f-e580-4103-a516-d3d7664c1cef.png)
![image](https://user-images.githubusercontent.com/22727114/187569341-8f225f8e-c869-460b-8f4e-a39ee6d637e4.png)

**Comment by LambdAurora** [comment]
Should be fixed now.

Guess who messed up CSS classes in the auto-generated page.
